import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createServiceClient } from '@/lib/supabase/server';

export async function POST(request: NextRequest) {
  try {
    const { name } = await request.json();

    if (!name || !name.trim()) {
      return NextResponse.json({ error: 'Box name is required' }, { status: 400 });
    }

    // Get the authenticated user
    const supabaseAuth = await createClient();
    const { data: { user } } = await supabaseAuth.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Use service role to bypass RLS for atomic box creation
    const supabase = await createServiceClient();

    // Create the box (slug auto-generated by DB)
    const { data: box, error: createError } = await supabase
      .from('boxes')
      .insert({ name: name.trim(), owner_id: user.id })
      .select('id, slug, name, invite_code')
      .single();

    if (createError) {
      return NextResponse.json({ error: createError.message }, { status: 500 });
    }

    // Add owner as a member
    await supabase
      .from('box_members')
      .insert({ box_id: box.id, user_id: user.id, role: 'owner' });

    // Create default #general channel
    await supabase
      .from('channels')
      .insert({ box_id: box.id, name: 'general', description: 'General discussion', created_by: user.id });

    return NextResponse.json({ box });
  } catch (error) {
    console.error('Create box error:', error);
    return NextResponse.json({ error: 'Failed to create box' }, { status: 500 });
  }
}
